### ISSUE TITLE
Suddenly Getting HTTP 500's

### ISSUE THREAD

**Issue by jerhewet** [MaxCDN/rws-bugs#11]
Any idea why code that hasn't been touched since 30MAY13 (when I had to change the API credentials) is suddenly returning this JSON response:

{"code":500,"error":{"message":"Invalid signature","type":"RWS\Exception"}}

Invalid signature?  Huh?  What?  Do I need to rewrite something on my end?

Jerry (Dazed And Confused) H.

**Comment by jerhewet** [comment]
Seems to have fixed itself in the past 15 minutes (!).  Pretty scarey error response, though... would prefer something a lot less terrifying, like "server unavailable" or "maintenance in progress".  :-;

Jerry (Happy Camper) H.

**Comment by eamonnscu** [comment]
Hey Jerry,

This seems very unusual. The last update we made to our API was 4 days ago. Not sure why you would have been receiving Invalid Signature because if the API was unreachable you would be getting a 502 error, not a 500.

Was this specific to a certain API endpoint or was it happening for all requests you sent?

Im interested to find out what was happening because the response does not seem like a normal network outage or anything of that sort

**Comment by jerhewet** [comment]
Was executing "cache.purge" calls with just one file in the POST when the 500 errors were being returned, but by the time the error emails trickled into my inbox and I ran some tests in my browser using the RESTClient addin (http://restclient.net/, btw -- excellent little addin for FireFox) things were back to normal.  So aside from the JSON responses in the error email there isn't anything useful to report.

Couldn't have been more than ten or fifteen minutes between the time I posted the JSON above for the bug and then went back to use RESTClient for testing.  Damned internets! :-)

**Comment by jerhewet** [comment]
Hate to say it, but the errors are back again, and the API servers haven't seemed to come back online(?).  Still the same response as before, and now I have 349 of 'em over the past two hours.

**Comment by eamonnscu** [comment]
Digging into this now, seems to be pretty sporadic. What response message are you getting along with the 500 status code?

**Comment by eamonnscu** [comment]
Is it an Invalid Signature?

**Comment by jerhewet** [comment]
If there's an "oauth_signature" parameter in the querystring of the URL that contains a plus sign, the plus sign(s) have to be replaced with "%2B" (http://stackoverflow.com/questions/9336267/url-encode-oauth-signature).

Good catch by eamonnscu!  Again! :-)

**Comment by dasvis** [comment]
I have the same problem, i get when i try to purge some file.

```
{"code":500,"error":{"message":"Invalid signature","type":"RWS\\Exception"}}
```

I haven't any plus sign on querystrig of the URL.

Any idea?

**Comment by jdorfman** [comment]
@dasvis please email support@maxcdn.com and they will dig into this for you.
