### ISSUE TITLE
POST and DELETE actions *SEEM* to be running slow...

### ISSUE THREAD

**Issue by jmervine** [MaxCDN/rws-bugs#13]
Hey,

I've been running some tests in both ruby and node and I'm seeing 20 - 30 seconds on getting a response from POST and DELETE methods. Oddly, when posting a new pull zone, it seems to show up in the web interface almost immediately, but the response doesn't come back quickly.

GET and PUT requests seem to be fine.

Cheers,
Josh

**Comment by chrisueland** [comment]
hey Josh - do you want someone to check out the server side?

**Comment by jmervine** [comment]
@chrisueland It seems like there's something off. If you guys are backing the rws with nginx, you should be able to pull POST or DELETE  requests vs. GET or PUT from the access logs and assuming you have nginx configured to show response times, it would be pretty clear if there's slower responses times. 

All that said, I haven't had time to try curl's vs. node and ruby clients, or try it from different locations, so it could be on my end. I only have the one account that can POST, so I can't really test much variation.

Josh

**Comment by eamonnscu** [comment]
@jmervine would you let me know what particular call was giving you trouble? Our POST and DELETE calls typically need to hit our edge servers to update your zones configuration. We were experiences some issues with this in Los Angeles during the time you reported the issue and I think this may have been involved: http://status.maxcdn.com/incidents/z6glctqpb9py. Would you be able to test this call again and let me know if the issue persists?

**Comment by jmervine** [comment]
@eamonnscu Sure thing, here's the script I was running...

https://github.com/jmervine/ruby-maxcdn/blob/master/test/integration.rb

It's a suite of integration tests I'm working on. When I originally ran it the `test_post_and_delete` and `test_purge` tests were taking between 60 and 90 seconds. They seem to be a bit faster now.

```
Started

Client
  test_get                                                        PASS (2.48s)
  test_purge                                                      PASS (44.57s)
  test_post_and_delete                                            PASS (36.64s)
  test_put                                                        PASS (1.01s)

Finished in 84.70390s
4 tests, 10 assertions, 0 failures, 0 errors, 0 skips
```

Here's a quick breakdown of what each is doing:

```
test_get == 4 x get requests
test_purge ==  1 get request and 3 purge requests (or 4 x delete requests)
test_post_and_delete == 1 post request and 1 delete request
test_put == 1 put request
```

I'll leave it up to you as to weather that's fast enough, but it seems okay to me.

Cheers,
Josh

**Comment by jmervine** [comment]
I rolled a quick benchmark script, which benchmarks each call here:

https://github.com/jmervine/ruby-maxcdn/blob/master/test/benchmark.rb

And here's the results of my initial run:

```
$ bundle exec ruby ./test/benchmark.rb
Running benchmarks as follows in order:

 maxcdn.get('zones/pull.json')
 maxcdn.get('reports/popularfiles.json')
 maxcdn.post('zones/pull.json', { :name => 'NAM', :url => 'URL' })
 maxcdn.put('account.json', { :name => 'NAME' })
 maxcdn.delete('zones/pull.json/ZONEID')
 maxcdn.purge('ZONEID')
 maxcdn.purge('ZONEID', 'FILE')
 maxcdn.purge('ZONEID', [ 'FILE1','FILE2' ])

       user     system      total        real
get   :  0.050000   0.060000   0.110000 (  0.924149)
get   :  0.010000   0.000000   0.010000 (  0.572340)
post  :  0.030000   0.000000   0.030000 ( 16.687296)
put   :  0.020000   0.000000   0.020000 (  1.095128)
delete:  0.020000   0.010000   0.030000 ( 11.571520)
purge :  0.030000   0.000000   0.030000 ( 18.554502)
purge :  0.020000   0.000000   0.020000 ( 21.184004)
purge :  0.020000   0.010000   0.030000 ( 24.550703)

```
