### ISSUE TITLE
Error pulling javascript file thru cdn

### ISSUE THREAD

**Issue by pclaar** [MaxCDN/rws-bugs#3]
This seemed to break either today or in the past couple of days.  I'm getting 500 errors for this URL:

http://maxcdn.claarware.com/wsAJAX.asmx/js

the source URL, which works fine, is

http://www.schooldigger.com/wsAJAX.asmx/js

**Comment by jdorfman** [comment]
Hey @pclaar is this related to the API or just the CDN?  If it is CDN only please email support at maxcdn/netdna dot com

**Comment by pclaar** [comment]
Sorry, it's the CDN.  And now I'm not seeing 500 errors so perhaps the error was fixed.  Thx,.
