### ISSUE TITLE
Req: Push zone is-sync-completed API check? Or ideas how to do without? :)

### ISSUE THREAD

**Issue by kristleifur** [MaxCDN/rws-bugs#5]
Hi,
Would it be possible to add an API call that checks whether a particular push zone upload has been synchronised to the edges?

I'd like to build a small web service app to manage installer downloads of some software. I'd like to be able to transfer the newest installer via SFTP to our master fileserver. The app would detect new content and upload it via API calls to a NetDNA/MaxCDN push zone. Then when users request the installer, the app would know somehow whether the content has been pushed out to all edge servers or not. Probably by running a recurring task that checks the NetDNA API from time to time if pending syncs are complete. If the file has been synced to the edges, the small app forwards users that are requesting downloads to the push zone CDN download. If not, the requested downloads are served directly from the master fileserver.

Any ideas on how to best accomplish something like this would also be most appreciated.

(This could be handled in JavaScript client-side I guess by just trying to download the file from the CDN, but I'd actually really like to do this in a minimal server-side app. Feel it would be more robust against silly outdated browsers.)

**Comment by dlitvakb** [comment]
@AnthonBerg Yesterday we've added this call to our latest release.

It's called Cache Inspector for Push Zones.

With this call you can check for individual files being present on each of the Edges

For having access to it you have to request Developer Tools to be enabled to your account

**Comment by kristleifur** [comment]
Nice!! Thank you!
