### ISSUE TITLE
setting ip address when creating pullzone

### ISSUE THREAD

**Issue by hezten** [MaxCDN/rws-bugs#6]
Hi

I was refered to this forum from the maxcdn support, as i have issus with creating pullzones and setting custom ip adress using the api.

In the api documentatiopn it says

ip  -   length: 1-10 chars, only digits accepted    Valid IP address of the Origin URL. If omitted, the service will try to lookup the IP automatically.    1.0

The question is, how do i provide an ip adresse only using digits and max 10 characters ? 100.100.100.100 is alone 12 digits and 3 .´s

I have tried the following calls

require_once('NetDNA.php');

$api = new NetDNA("bloggersdelight","secret","secret");
try {

```
        $params = array('name' => 'tonnytest6',
                        'url' => 'http://erdettirsdag.dk',
                        'ip' => '86.48.100.46',
                        'compress' => '1',
                        'use_stale' => '1',
                        'expires' => '12M');
```

   echo  $api->post('/zones/pull.json',$params);
} catch(CurlException $e) {
 print_r($e->getMessage());
 print_r($e->getHeaders());
}

and also tried sending the ip as decimal

require_once('NetDNA.php');

$api = new NetDNA("bloggersdelight","secret","secret");
try {

```
        $params = array('name' => 'tonnytest6',
                        'url' => 'http://erdettirsdag.dk',
                        'ip' => ip2long('86.48.100.46'),
                        'compress' => '1',
                        'use_stale' => '1',
                        'expires' => '12M');
```

   echo  $api->post('/zones/pull.json',$params);
} catch(CurlException $e) {
 print_r($e->getMessage());
 print_r($e->getHeaders());
}

both just sets the ip adresse to the resolve ip of the erdettirsdag.dk domain. I need to specifi another ip as we have a dedicated server for providing assets to pull zones.

**Comment by jdorfman** [comment]
@hezten Your zone has the DNS Resolver enabled on your zone so updating the Origin IP is pointless.  If you have any other questions please email me jdorfman at netdna dot com

**Comment by hezten** [comment]
i cant see how i disable that on the documentation here https://developer.netdna.com/api/docs#pcreatePullZone

The zone was created with the above call, how would that enable dns resolve for the zone ?

**Comment by jdorfman** [comment]
@hezten All zones created have it enabled by default.  It is ~~our~~ my fault for the poor documentation.  We are currently working to improve our docs.  Preview here: http://note.io/11apc69

Please feel free to email me with any suggestions: jdorfman at netdna dot com
