### ISSUE TITLE
REST API Equivalent Of cache.purgeAllCache

### ISSUE THREAD

**Issue by jerhewet** [MaxCDN/rws-bugs#7]
Will the REST API have an endpoint for clearing everything in a pull zone?  The existing XML-RPC API has a command for purging the entire pull zone -- cache.purgeAllCache -- and I'm not finding an equivalent for the new REST API.

I've been doing some testing on our staging server, and (oddly enough) passing a wildcard for the filename does seem to be working.  I think.

https://rws.netdna.com/[company alias]/zones/pull.json/[zone ID]/cache
file=_._

If there aren't any plans for supporting the REST equivalent of cache.purgeAllCache _and_ you don't plan to eliminate support for wildcards, then this issue becomes moot.

But if wildcards really aren't working (although testing seems to indicate otherwise) then we'll need an endpoint that _does_ purge the entire pull zone.

**Comment by dlitvakb** [comment]
@jerhewet you can use DELETE /zones/pull.json/{zone_id}/cache with no parameters to replicate that functionality

Feel free to ask if you have any further questions

**Comment by jerhewet** [comment]
@dlitvakb Does this new functionality also offer us the ability to purge subdirectories within a particular zone?  For example, would the following REST call purge all of the cached content in "foo"?

DELETE /zones/pull.json/{zone_id}/cache
"file"="/foo/"

**Comment by jdorfman** [comment]
@jerhewet Sorry for the delay.  At this time there is no support for wildcards and/or by directory.  Just single and full purge.
