### ISSUE TITLE
Reports By File Name API

### ISSUE THREAD

**Issue by apd1** [MaxCDN/rws-bugs#9]
Is this active I seem to have trouble getting a response? Do you have any sample php code?

**Comment by eamonnscu** [comment]
@apd1 Yes it is, are you using our PHP library or a custom implementation? If so here is sample code for the most basic usage: https://gist.github.com/pascalscu/5365605

See documentation here about passing in date ranges: https://developer.netdna.com/api/docs

The doc actually needs to be updated but you can also pass nopaginate=1 to eliminate pagination

**Comment by eamonnscu** [comment]
If so should have read: If you are using our Library,

**Comment by apd1** [comment]
Yep I'm using your PHP library but I'm not sure how to use the statsbyfilename?

**Comment by apd1** [comment]
I'm basically after a way to get the number of hits an individual file has had in total or between a particular date, is this possible?

**Comment by eamonnscu** [comment]
This is possible but is not available by default. The resource that you are trying to access is actually an Advanced Reporting Feature, again this should have been noted in the documentation I apologize. 

Why don't you shoot at an email to jdorfman@netdna.com and he can provide you with more details to get this enabled on your account. I've already let him know to expect an email
